name: Deploy Server

on:
  push:
    branches: [ main ]
    
env:
  REPO: extension-blocking
  DIR: .
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11    
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Make gradle excutable
      run: chmod +x gradlew 
      working-directory: ${{env.DIR}}

    - name: Build with Gradle 
      run: ./gradlew bootJar
      working-directory: ${{env.DIR}}

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ${{env.DIR}}
        file: ${{env.DIR}}/Dockerfile
        push: true
        tags: ${{secrets.DOCKERHUB_USERNAME}}/${{env.REPO}}:latest

  deploy:
    needs: build
    name: Deploy
    runs-on: [ self-hosted, label-development ]
    steps:

      - name: deploy run
        run: |
          sudo sh /home/ec2-user/run.sh
